---
label: Product
hide_body: false
fields:
- type: text
  name: title
  label: title
- type: datetime
  name: date
  label: date
  hidden: true
- type: image_gallery
  name: images
  label: images
- type: text
  name: description
  label: description
  hidden: true
